package com.marlo.construction.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MGTBusinessData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MGTBusinessData() {
    }

}