package com.marlo.construction;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommonProcessTask implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CommonProcessTask() {
    }

}