package com.marlo.pms.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.marlo.construction.common.CommonProcessTask taskData;

   public ApplicationData()
   {
   }

   public com.marlo.construction.common.CommonProcessTask getTaskData()
   {
      return this.taskData;
   }

   public void setTaskData(
         com.marlo.construction.common.CommonProcessTask taskData)
   {
      this.taskData = taskData;
   }

   public ApplicationData(
         com.marlo.construction.common.CommonProcessTask taskData)
   {
      this.taskData = taskData;
   }

}