package com.marlo.pms.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.marlo.pms.common.CommonProcessTask taskData;

   private com.marlo.pms.common.MGTBusinessData mgtBusinessData;

   public ApplicationData()
   {
   }

   public com.marlo.pms.common.CommonProcessTask getTaskData()
   {
      return this.taskData;
   }

   public void setTaskData(
         com.marlo.pms.common.CommonProcessTask taskData)
   {
      this.taskData = taskData;
   }

   public com.marlo.pms.common.MGTBusinessData getMgtBusinessData()
   {
      return this.mgtBusinessData;
   }

   public void setMgtBusinessData(
         com.marlo.pms.common.MGTBusinessData mgtBusinessData)
   {
      this.mgtBusinessData = mgtBusinessData;
   }

   public ApplicationData(com.marlo.pms.common.CommonProcessTask taskData,
         com.marlo.pms.common.MGTBusinessData mgtBusinessData)
   {
      this.taskData = taskData;
      this.mgtBusinessData = mgtBusinessData;
   }

}