package com.marlo.pms.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ApplicationData() {
    }

}