package com.marlo.pms.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Attachment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String title;
   private comorg.jbpm.document.Document document;

   public Attachment()
   {
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public org.jbpm.document.Document getDocument()
   {
      return this.document;
   }

   public void setDocument(org.jbpm.document.Document document)
   {
      this.document = document;
   }

   public Attachment(java.lang.String title,
         org.jbpm.document.Document document)
   {
      this.title = title;
      this.document = document;
   }

}