package com.marlo.pms.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MGTBusinessData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String description;

   private java.util.List<com.marlo.pms.common.Attachment> attachments;

   public MGTBusinessData()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.util.List<com.marlo.pms.common.Attachment> getAttachments()
   {
      return this.attachments;
   }

   public void setAttachments(
         java.util.List<com.marlo.pms.common.Attachment> attachments)
   {
      this.attachments = attachments;
   }

   public MGTBusinessData(java.lang.String name, java.lang.String description,
         java.util.List<com.marlo.pms.common.Attachment> attachments)
   {
      this.name = name;
      this.description = description;
      this.attachments = attachments;
   }

}