package com.marlo.pms.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MGTApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MGTApplication() {
    }

}