package com.marlo.pms.management;

import com.marlo.pms.common.ApplicationData;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MGTApplication extends ApplicationData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.marlo.pms.management.MGTBusinessData businessData;

   public MGTApplication()
   {
   }

   public com.marlo.pms.management.MGTBusinessData getBusinessData()
   {
      return this.businessData;
   }

   public void setBusinessData(
         com.marlo.pms.management.MGTBusinessData businessData)
   {
      this.businessData = businessData;
   }

   public MGTApplication(com.marlo.pms.management.MGTBusinessData businessData)
   {
      this.businessData = businessData;
   }

}